#!/bin/sh

set -e

test -d ~/.vim || mkdir -p ~/.vim

cp -r ./vimrcs ~/.vim/

echo '" DO NOT EDIT THIS FILE
source ~/.vim/vimrcs/basic.vim
source ~/.vim/vimrcs/plugins.vim
source ~/.vim/vimrcs/vundle.vim
' > ~/.vimrc

cp -r plugin ~/.vim/
cp -r autoload ~/.vim/

echo "Installed the vim configuration successfully! Enjoy :-)"
