#!/bin/bash

set -e

ROOT_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)

# read -t 5 -p "press any key to continue (wait for 3 mins)..." answer

normal_install() {
	test -d ~/.vim || mkdir -p ~/.vim
	
	cp -r ./vimrcs ~/.vim/
	
	echo '" DO NOT EDIT THIS FILE
	source ~/.vim/vimrcs/basic.vim
	source ~/.vim/vimrcs/plugins.vim
	' > ~/.vimrc
	
	echo "Installed the vim configuration successfully! Enjoy :-)"
}

direct_install() {
	echo '" DO NOT EDIT THIS FILE' >> ~/.vimrc
	cat vimrcs/basic.vim >> ~/.vimrc
	cat vimrcs/plugins.vim >> ~/.vimrc
}

developp_install() {
	echo "source ${ROOT_DIR}/init.vim" > ~/.vimrc
	echo "Installed the vim configuration successfully!"
}

if [ $# == 0 ]
then
	normal_install
elif [ $# == 1 ]
then
	case $1 in
	dev*)
		developp_install
	;;
	normal)
		normal_install
	;;
	direct)
		direct_install
	;;
	*)
			echo "Error: wrong parameter. Please enter again."
		;;
	esac
else
	echo "Error: too many parameters!"
fi
